# 01 예외처리
## 1. 오류는 어떤 떄 발생하는가?
### 1. 없는 파일
```
>>> f = open("null",'r')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'null'
```
### 2. x/0
```
>>> 4/0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
```
### 3. 없는 요소
```
>>> a=[1,2,3]
>>> a[4]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
```